AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for serverless Lambda function

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ContactFormFunction
      Handler: app.lambda_handler
      CodeUri: sam-backend/
      Events:
        Api:
          Type: Api
          Properties:
            Path: /contact
            Method: post

Outputs:
  ContactFormApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"
