AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template with simplified CORS

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
      AllowOrigin: "'*'"

Resources:
  ContactFormApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ContactFormApi
      StageName: Prod

  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ContactFormFunction
      Handler: app.lambda_handler
      CodeUri: sam-backend/
      Events:
        ContactPost:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId: !Ref ContactFormApiGateway
        ContactGet:
          Type: Api
          Properties:
            Path: /contact
            Method: get
            RestApiId: !Ref ContactFormApiGateway
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  ContactFormApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ContactFormApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"
