AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template with simple CORS configuration per method

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ContactFormFunction
      Handler: app.lambda_handler
      CodeUri: sam-backend/
      Events:
        ContactPost:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId: !Ref ContactFormApiGateway
            Auth:
              Authorizer: NONE
            Cors: true
        ContactGet:
          Type: Api
          Properties:
            Path: /contact
            Method: get
            RestApiId: !Ref ContactFormApiGateway
            Auth:
              Authorizer: NONE
            Cors: true

  ContactFormApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ContactFormApi
      StageName: Prod
