AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for serverless Lambda function with simplified CORS

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ContactFormFunction
      Handler: app.lambda_handler
      CodeUri: sam-backend/
      Events:
        ContactPost:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId: !Ref ContactFormApiGateway
            Auth:
              Authorizer: NONE
        ContactGet:
          Type: Api
          Properties:
            Path: /contact
            Method: get
            RestApiId: !Ref ContactFormApiGateway
            Auth:
              Authorizer: NONE

  ContactFormApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ContactFormApi
      StageName: Prod
      Cors: true

Outputs:
  ContactFormApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ContactFormApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"
