AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: t_sam_func_contact_form
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: lambda/
      Timeout: 10
      Policies: AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /contact
            Method: ANY

  ContactFormS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-bucket"
      WebsiteConfiguration:
        IndexDocument: contact.html
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

Outputs:
  LambdaFunctionArn:
    Description: "The ARN of the Lambda function"
    Value: !GetAtt ContactFormFunction.Arn

  ApiGatewayEndpoint:
    Description: "The API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"

  S3BucketName:
    Description: "The name of the S3 bucket used for static website hosting"
    Value: !Ref ContactFormS3Bucket

  S3WebsiteURL:
    Description: "The URL of the S3 static website"
    Value: !GetAtt ContactFormS3Bucket.WebsiteURL