service: contact-form-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-2
  stage: dev
  memorySize: 128
  timeout: 10
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
  httpApi:
    cors: true # This enables CORS for all endpoints

functions:
  contactFormHandler:
    handler: app.lambda_handler
    events:
      - http:
          path: /contact
          method: post
          cors: true # Explicit CORS for POST
      - http:
          path: /contact
          method: get
          cors: true # Explicit CORS for GET
