name: Deploy Infrastructure

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-2
  TF_VERSION: 1.5.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Linter
        run: |
          pip install flake8
          flake8 lambda/

      - name: Run Unit Tests
        run: |
          cd lambda
          pip install pytest
          pytest tests/ -v

      - name: Package Lambda Function
        run: |
          cd lambda
          pip install -r requirements.txt -t ./package
          cd package && zip -r ../lambda.zip .
          cd .. && zip -g lambda.zip app.py
          mv lambda.zip ../

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name myapp \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify Deployment
        run: |
          echo "Testing API endpoint..."
          curl -s "$(terraform output -raw api_gateway_url)" | jq .