name: Deploy SAM Application

on:
  push:
    branches:
      - aws-sam
    paths:
      - 'sam-backend/**'
      - 'sam-template.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy with SAM
    runs-on: ubuntu-latest
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install AWS SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  

    - name: SAM Build
      run: sam build --template sam-template.yaml

    - name: SAM Deploy
      run: |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name sam-contact-form \
          --capabilities CAPABILITY_IAM \
          --region us-east-2 \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset
