name: Deploy SAM Application

on:
  push:
    branches: [aws-sam]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  STACK_NAME: contact-form-api

jobs:
  deploy:
    name: Build and Deploy with SAM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate SAM template
        run: sam validate --template sam-template.yaml

      - name: Build SAM application
        run: sam build --template sam-template.yaml

      - name: Deploy SAM application
        run: |
          sam deploy \
            --stack-name $STACK_NAME \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset
