name: Deploy SAM Application

on:
  push:
    branches: [aws-sam]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  STACK_NAME: contact-form-api

jobs:
  deploy:
    name: Build and Deploy with SAM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate SAM template
        run: sam validate --template sam-template.yaml

      - name: Build SAM application
        run: sam build --template sam-template.yaml

      - name: Clean Up Stuck Stack
        run: |
          aws cloudformation continue-update-rollback \
            --stack-name contact-form-api \
            --region us-east-2 || true

          sleep 120
          aws cloudformation describe-stacks \
            --stack-name contact-form-api \
            --query 'Stacks[0].StackStatus' \
            --output text | grep -q 'UPDATE_ROLLBACK_FAILED' && \
          aws cloudformation delete-stack \
            --stack-name contact-form-api \
            --region us-east-2

          aws cloudformation wait stack-delete-complete \
            --stack-name contact-form-api \
            --region us-east-2 || true

      - name: Deploy Fresh
        run: |
          sam deploy \
            --stack-name contact-form-api \
            --region us-east-2 \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --force-upload
