name: "AWS SAM CI/CD"

on:
  workflow_dispatch:
  push:
    branches: [toral_ci-cd-aws-sam]

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: "Deploy to AWS"
    runs-on: ubuntu-latest

    steps:
      - name: "Step | Checkout Code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
        continue-on-error: false

      - name: "Step | Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
        continue-on-error: false

      - name: "Step | Run PyTest"
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/aws_sam/lambda
          cd aws_sam/lambda
          pip install -r requirements.txt
          pytest tests/ -v
        continue-on-error: false

      - name: "Step | AWS SAM CLI"
        run: |
          pip install aws-sam-cli
        continue-on-error: false

      - name: "Step | Setup AWS Creds"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: false

      - name: "Step | SAM Build"
        run: |
          cd aws_sam
          sam build --use-container
        continue-on-error: false

      - name: "Step | SAM Deploy"
        id: sam_deploy
        run: |
          cd aws_sam
          sam deploy --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
        continue-on-error: false

      - name: "Step | Extract API Endpoint"
        id: extract_api
        run: |
          API_ENDPOINT=$(aws cloudformation describe-stacks --stack-name t-sam-stack-contact-form --query "Stacks[0].Outputs[?OutputKey=='ApiGatewayEndpoint'].OutputValue" --output text)
          echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_ENV
        continue-on-error: false

      - name: "Step | Validate API Endpoint"
        run: |
          echo "Validating API Endpoint: $API_ENDPOINT"
          curl -X GET $API_ENDPOINT
        continue-on-error: false
